general:
  show_welcome:
    type: bool
    default: true
  updates:
    check:
      type: bool
      default: true
  screenshot_dir: string
  skip_boot_anim: bool
  # throttle_io: bool
  last_viewed_menu_index: integer
  user_token: string

input:
  bindings:
    port1: string
    port2: string
    port3: string
    port4: string
  gamecontrollerdb_path: string
  auto_bind:
    type: bool
    default: true
  background_input_capture: bool
  keyboard_controller_scancode_map:
    # Scancode reference : https://github.com/libsdl-org/SDL/blob/main/include/SDL_scancode.h
    a:
      type: integer
      # default key : a (4)
      default: 4
    b:
      type: integer
      # default key : b (5)
      default: 5
    x:
      type: integer
      # default key : x (27)
      default: 27
    y:
      type: integer
      # default key : y (28)
      default: 28
    dpad_left:
      type: integer
      # default key : left (80)
      default: 80
    dpad_up:
      type: integer
      # default key : up (82)
      default: 82
    dpad_right:
      type: integer
      # default key : right (79)
      default: 79
    dpad_down:
      type: integer
      # default key : down (81)
      default: 81
    back:
      type: integer
      # default key : backspace (42)
      default: 42
    start:
      type: integer
      # default key : return (40)
      default: 40
    white:
      type: integer
      # default key : 1 (30)
      default: 30
    black:
      type: integer
      # default key : 2 (31)
      default: 31
    lstick_btn:
      type: integer
      # default key : 3 (32)
      default: 32
    rstick_btn:
      type: integer
      # default key : 4 (33)
      default: 33
    guide:
      type: integer
      # default key : 5 (34)
      default: 34
    lstick_up:
      type: integer
      # default key : e (8)
      default: 8
    lstick_left:
      type: integer
      # default key : s (22)
      default: 22
    lstick_right:
      type: integer
      # default key : f (9)
      default: 9
    lstick_down:
      type: integer
      # default key : d (7)
      default: 7
    ltrigger:
      type: integer
      # default key : w (26)
      default: 26
    rstick_up:
      type: integer
      # default key : i (12)
      default: 12
    rstick_left:
      type: integer
      # default key : j (13)
      default: 13
    rstick_right:
      type: integer
      # default key : l (15)
      default: 15
    rstick_down:
      type: integer
      # default key : k (14)
      default: 14
    rtrigger:
      type: integer
      # default key : w (18)
      default: 18

display:
  quality:
    surface_scale:
      type: integer
      default: 1
  window:
    fullscreen_on_startup: bool
    startup_size:
      type: enum
      values: [last_used, 640x480, 1280x720, 1280x800, 1280x960, 1920x1080, 2560x1440, 2560x1600, 2560x1920, 3840x2160]
      default: 1280x960
    last_width:
      type: integer
      default: 640
    last_height:
      type: integer
      default: 480
    vsync:
      type: bool
      default: true
  ui:
    show_menubar:
      type: bool
      default: true
    use_animations:
      type: bool
      default: true
    fit:
      type: enum
      values: [center, scale, scale_16_9, scale_4_3, stretch]
      default: scale
    scale:
      type: integer
      default: 1
    auto_scale:
      type: bool
      default: true

audio:
  use_dsp: bool
  volume_limit:
    type: number
    default: 1

net:
  enable: bool
  backend:
    type: enum
    values: [nat, udp, pcap]
    default: nat
  pcap:
    netif: string
  udp:
    bind_addr:
      type: string
      default: 0.0.0.0:9368
    remote_addr:
      type: string
      default: 1.2.3.4:9368
  nat:
    forward_ports:
      type: array
      items:
        host: integer
        guest: integer
        protocol:
          type: enum
          values: [tcp, udp]
          default: tcp

sys:
  mem_limit:
    type: enum
    values: ['64', '128']
    default: '64'
  avpack:
    type: enum
    values: [scart, hdtv, vga, rfu, svideo, composite, none]
    default: hdtv
  files:
    bootrom_path: string
    flashrom_path: string
    eeprom_path: string
    hdd_path: string
    dvd_path: string

perf:
  hard_fpu:
    type: bool
    default: true
  # cache_shaders:
  #   type: bool
  #   default: true
